/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamo.Formularios;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import prestamo.Colaboradores.ConsultaPrestamoColaborador;
import prestamo.Modelo.Cliente;

/**
 *
 * @author Cesar
 */
public class ConsultaPrestamo extends javax.swing.JFrame {
    private ConsultaPrestamoColaborador colaborador;
    private Integer idClienteSeleccionado;
    private Hashtable clientes = new Hashtable<>();
    private int idCliente; 
    /**
     * Creates new form ConsultaPrestamo
     */
    public ConsultaPrestamo() {
        initComponents();
        setDatosIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConsultaPrestamo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrestamo = new javax.swing.JTable();
        lblCliente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlTituloAdministracionCliente = new javax.swing.JPanel();
        lblTituloAdminCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlListaCliente = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList();
        btnBorrarClienteSeleccionado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlConsultaPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        pnlConsultaPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlConsultaPrestamoMouseClicked(evt);
            }
        });

        jtPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPrestamoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPrestamo);

        lblCliente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCliente.setText("Filtros");

        pnlTituloAdministracionCliente.setBackground(java.awt.Color.black);

        lblTituloAdminCliente.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblTituloAdminCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloAdminCliente.setText("Consulta de Prestamo");

        javax.swing.GroupLayout pnlTituloAdministracionClienteLayout = new javax.swing.GroupLayout(pnlTituloAdministracionCliente);
        pnlTituloAdministracionCliente.setLayout(pnlTituloAdministracionClienteLayout);
        pnlTituloAdministracionClienteLayout.setHorizontalGroup(
            pnlTituloAdministracionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAdministracionClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAdminCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloAdministracionClienteLayout.setVerticalGroup(
            pnlTituloAdministracionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAdministracionClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAdminCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setText("Cliente");

        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lstClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstClientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstClientes);

        javax.swing.GroupLayout pnlListaClienteLayout = new javax.swing.GroupLayout(pnlListaCliente);
        pnlListaCliente.setLayout(pnlListaClienteLayout);
        pnlListaClienteLayout.setHorizontalGroup(
            pnlListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        pnlListaClienteLayout.setVerticalGroup(
            pnlListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaClienteLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        btnBorrarClienteSeleccionado.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cesar\\Downloads\\DeleteImage.png")); // NOI18N
        btnBorrarClienteSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarClienteSeleccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultaPrestamoLayout = new javax.swing.GroupLayout(pnlConsultaPrestamo);
        pnlConsultaPrestamo.setLayout(pnlConsultaPrestamoLayout);
        pnlConsultaPrestamoLayout.setHorizontalGroup(
            pnlConsultaPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloAdministracionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlConsultaPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsultaPrestamoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addGroup(pnlConsultaPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlListaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarClienteSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        pnlConsultaPrestamoLayout.setVerticalGroup(
            pnlConsultaPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaPrestamoLayout.createSequentialGroup()
                .addComponent(pnlTituloAdministracionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultaPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBorrarClienteSeleccionado)
                    .addComponent(txtCliente)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addComponent(pnlListaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConsultaPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConsultaPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarClienteSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarClienteSeleccionadoActionPerformed
        txtCliente.setEditable(true);
        txtCliente.setText("");
        btnBorrarClienteSeleccionado.setVisible(false);
        colaborador.SetDefaultModel();
    }//GEN-LAST:event_btnBorrarClienteSeleccionadoActionPerformed

    private void lstClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstClientesMouseClicked
        String keyHash = lstClientes.getSelectedValue().toString();
        idClienteSeleccionado = Integer.parseInt(clientes.get(keyHash).toString());
        Cliente cliente = colaborador.GetClienteById(idClienteSeleccionado);
        txtCliente.setText(colaborador.getNombreCompleto(cliente));
        txtCliente.setEditable(false);
        btnBorrarClienteSeleccionado.setVisible(true);
        pnlListaCliente.setVisible(false);

    }//GEN-LAST:event_lstClientesMouseClicked

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        List<Cliente> clientesSearch = new ArrayList<>();
        String letraIngresada = Character.toString(evt.getKeyChar()).trim();
        String palabraIngresada = txtCliente.getText()+ letraIngresada;
        if(!"".equals(palabraIngresada)) {
            clientesSearch = colaborador.GetClienteBySearch(palabraIngresada);
        }

        if(!clientesSearch.isEmpty()){
            pnlListaCliente.setVisible(true);
            lstClientes.setModel(colaborador.getModelClientes(clientesSearch));
            for (Cliente c : clientesSearch) {
                clientes.put(colaborador.getNombreCompleto(c), c.getId());
            }
        }else{
            pnlListaCliente.setVisible(false);
        }
    }//GEN-LAST:event_txtClienteKeyTyped

    @SuppressWarnings("null")
    private void jtPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPrestamoMouseClicked
        Integer selectedRow = jtPrestamo.getSelectedRow();
        if (selectedRow != null){
            idCliente = Integer.parseInt(jtPrestamo.getValueAt(selectedRow, 0).toString());
        }
    }//GEN-LAST:event_jtPrestamoMouseClicked

    private void pnlConsultaPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConsultaPrestamoMouseClicked
        pnlListaCliente.setVisible(false);
        btnBorrarClienteSeleccionado.setVisible(false);
    }//GEN-LAST:event_pnlConsultaPrestamoMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        jtPrestamo.setModel(colaborador.GetModelPrestamos(idClienteSeleccionado));
        jtPrestamo.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jtPrestamo.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtPrestamo.getColumnModel().getColumn(0).setResizable(false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarClienteSeleccionado;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtPrestamo;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTituloAdminCliente;
    private javax.swing.JList lstClientes;
    public javax.swing.JPanel pnlConsultaPrestamo;
    private javax.swing.JPanel pnlListaCliente;
    private javax.swing.JPanel pnlTituloAdministracionCliente;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables

    private void setDatosIniciales() {
        colaborador = new ConsultaPrestamoColaborador();
        pnlListaCliente.setVisible(false);
        btnBorrarClienteSeleccionado.setVisible(false);
    }
}
