/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prestamo.Formularios;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author R2D2
 */
public class MainCliente extends javax.swing.JFrame {

    /**
     * Creates new form MainCliente
     */    
    private AdministracionCliente administracionCliente;
    private ConsultaPrestamo consultaPrestamo;
    private int idCliente;
    

    public MainCliente() {
        initComponents();
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnNuevoCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnSeleccionarPrestamo = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        JMIPrestamoSimple = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIConsultaPrestamo = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(897, 558));
        setResizable(false);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnModificarCliente.setText("Modificar Cliente");
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        btnSeleccionarPrestamo.setText("Seleccione Prestamo");
        btnSeleccionarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPrestamoActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionarPrestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeleccionarPrestamo)
                    .addComponent(btnVolver))
                .addContainerGap())
        );

        jMenu1.setText("Administración");

        jMenuItem1.setText("Nuevo cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ver clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Nuevo Préstamo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        JMIPrestamoSimple.setText("Nuevo Préstamo Simple");
        JMIPrestamoSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIPrestamoSimpleActionPerformed(evt);
            }
        });
        jMenu1.add(JMIPrestamoSimple);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Prestamo");

        jMIConsultaPrestamo.setText("Consulta de prestamo");
        jMIConsultaPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsultaPrestamoActionPerformed(evt);
            }
        });
        jMenu4.add(jMIConsultaPrestamo);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addElement(JPanel panel){
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(panel);        
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        NuevoCliente nuevocliente = new NuevoCliente();
        addElement(nuevocliente.pnlAdministracionCliente); 
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        administracionCliente = new AdministracionCliente();
        addElement(administracionCliente.pnlAdministracionClienteForm);  
        jPanel2.setVisible(true);
        btnSeleccionarPrestamo.setVisible(false);
        btnVolver.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        PrestamoCliente prestamoCliente = new PrestamoCliente();
        addElement(prestamoCliente.pnlPrestamoCliente);   
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        NuevoCliente nuevocliente = new NuevoCliente();
        addElement(nuevocliente.pnlAdministracionCliente); 
        jPanel2.setVisible(false);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        int idCliente = this.administracionCliente.getIdCliente();
        if(idCliente != -1){
            NuevoCliente nuevocliente = new NuevoCliente(idCliente);
            addElement(nuevocliente.pnlAdministracionCliente); 
            jPanel2.setVisible(false);
        } else              
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Cliente", "Mensaje de Error", 1);
        
        
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void jMIConsultaPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsultaPrestamoActionPerformed
        consultaPrestamo = new ConsultaPrestamo();
        addElement(consultaPrestamo.pnlConsultaPrestamo); 
        jPanel2.setVisible(true);
        btnModificarCliente.setVisible(false);
        btnNuevoCliente.setVisible(false);
        btnSeleccionarPrestamo.setVisible(true);
        btnVolver.setVisible(false);
    }//GEN-LAST:event_jMIConsultaPrestamoActionPerformed

    private void btnSeleccionarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPrestamoActionPerformed
        int idPrestamo = consultaPrestamo.getIdPrestamo();
        idCliente = consultaPrestamo.getIdClienteSeleccionado();
        if(idPrestamo != -1){
            PrestamoCliente prestamoCliente = new PrestamoCliente(idPrestamo);
            addElement(prestamoCliente.pnlPrestamoCliente);
            jPanel2.setVisible(true);
            btnSeleccionarPrestamo.setVisible(false);
            btnVolver.setVisible(true);
        }
    }//GEN-LAST:event_btnSeleccionarPrestamoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        consultaPrestamo = new ConsultaPrestamo(idCliente);        
        if(consultaPrestamo != null){
            addElement(consultaPrestamo.pnlConsultaPrestamo);
            consultaPrestamo.loadPage();
            btnModificarCliente.setVisible(false);
            btnNuevoCliente.setVisible(false);
            btnSeleccionarPrestamo.setVisible(true);
            btnVolver.setVisible(false);
            
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void JMIPrestamoSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIPrestamoSimpleActionPerformed
        // TODO add your handling code here:
        PrestamoSimpleCliente prestamoSimpleCliente = new PrestamoSimpleCliente();
        addElement(prestamoSimpleCliente.pnlPrestamoCliente);   
        jPanel2.setVisible(false);
    }//GEN-LAST:event_JMIPrestamoSimpleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIPrestamoSimple;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnSeleccionarPrestamo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenuItem jMIConsultaPrestamo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
