/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prestamo.Formularios;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JOptionPane;
import prestamo.Colaboradores.NuevoClienteColaborador;
import prestamo.Modelo.Cliente;
import prestamo.Modelo.Conocido;
import prestamo.Modelo.Direccion;
import prestamo.Modelo.Garante;
import prestamo.Modelo.Validadores.ConocidoValidator;
import prestamo.Modelo.Validadores.ObjectValidator;

/**
 *
 * @author R2D2
 */
public class NuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoCliente
     */
    private NuevoClienteColaborador colaborador = new NuevoClienteColaborador();
    private Garante garante;
    private Hashtable conocidos = new Hashtable<>(); 
    private Integer idCliente;
    private Integer selectedIndexConocido;
    private List<Integer> conocidosABorrar ;
    
    public NuevoCliente() {
        initComponents();
        setDatosIniciales();
    }
    
    public NuevoCliente(int idCliente) {
        initComponents();
        setDatosIniciales();        
        setClienteFormulario(idCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdGarante = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txtCodigoPostalGarante = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDepartamentoGarante = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtPisoGarante = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNombreGarante = new javax.swing.JTextField();
        txtNumeroGarante = new javax.swing.JTextField();
        txtApellidoGarante = new javax.swing.JTextField();
        btnGuardarGarante = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtDomicilioGarante = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        pnlAdministracionCliente = new javax.swing.JPanel();
        pnlTituloAdministracionCliente = new javax.swing.JPanel();
        lblTituloNuevoCliente = new javax.swing.JLabel();
        pnlNuevoCliente = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblApellidoCliente = new javax.swing.JLabel();
        txtApellidoCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ddlDiaNacimiento = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ddlMesNacimiento = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        ddlAnioNacimiento = new javax.swing.JComboBox();
        lblDatosPersonales = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblNombre = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombreConocido = new javax.swing.JFormattedTextField();
        txtOtroTelefono = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOtroscontactos = new javax.swing.JList();
        btnAgregarConocido = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        ddlTipodocumento = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblGarante = new javax.swing.JLabel();
        btnGarante = new javax.swing.JButton();
        lblMesajeConfirmacion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtApellidoConocido = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDocCliente = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JFormattedTextField();

        jdGarante.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setText("Datos Garante");

        jLabel20.setText("Nombre");

        jLabel21.setText("Apellido");

        jLabel26.setText("Piso");

        jLabel27.setText("Nro");

        txtNombreGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreGaranteActionPerformed(evt);
            }
        });

        btnGuardarGarante.setText("Guardar");
        btnGuardarGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarGaranteActionPerformed(evt);
            }
        });

        jLabel23.setText("Calle");

        jLabel24.setText("Código Postal");

        jLabel25.setText("Departamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarGarante)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDepartamentoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPisoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDomicilioGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtApellidoGarante)
                            .addComponent(txtNombreGarante)
                            .addComponent(txtCodigoPostalGarante))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtDepartamentoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPisoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(txtDomicilioGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoPostalGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarGarante)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdGaranteLayout = new javax.swing.GroupLayout(jdGarante.getContentPane());
        jdGarante.getContentPane().setLayout(jdGaranteLayout);
        jdGaranteLayout.setHorizontalGroup(
            jdGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdGaranteLayout.setVerticalGroup(
            jdGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlAdministracionCliente.setPreferredSize(new java.awt.Dimension(897, 558));

        pnlTituloAdministracionCliente.setBackground(java.awt.Color.black);

        lblTituloNuevoCliente.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblTituloNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloNuevoCliente.setText("Nuevo cliente");

        pnlNuevoCliente.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreCliente.setText("Nombre");

        lblApellidoCliente.setText("Apellido");
        lblApellidoCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setText("Tipo de Documento");

        jLabel2.setText("Fecha de nacimiento");

        jLabel3.setText("Día");

        ddlDiaNacimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel4.setText("Mes");

        ddlMesNacimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel5.setText("Año");

        lblDatosPersonales.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDatosPersonales.setText("Datos personales");

        jLabel6.setText("Calle");

        jLabel7.setText("Código Postal");

        jLabel8.setText("Departamento");

        jLabel9.setText("Piso");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Contacto");

        jLabel12.setText("Teléfono");

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Celular");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("Otros contactos (Conocidos)");

        lblNombre.setText("Nombre");

        jLabel15.setText("Telefono");

        try {
            txtOtroTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lstOtroscontactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstOtroscontactosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstOtroscontactos);

        btnAgregarConocido.setText("+");
        btnAgregarConocido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarConocidoActionPerformed(evt);
            }
        });

        btnAgregarCliente.setText("Guardar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        jLabel16.setText("Nacionalidad");

        jLabel17.setText("Nro");

        jLabel18.setText("Nro");

        lblGarante.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGarante.setText("Garante");

        btnGarante.setText("Agregar Garante");
        btnGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaranteActionPerformed(evt);
            }
        });

        jLabel14.setText("Apellido");

        jLabel22.setText("Código");

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 204));

        try {
            txtDocCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        javax.swing.GroupLayout pnlNuevoClienteLayout = new javax.swing.GroupLayout(pnlNuevoCliente);
        pnlNuevoCliente.setLayout(pnlNuevoClienteLayout);
        pnlNuevoClienteLayout.setHorizontalGroup(
            pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createSequentialGroup()
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatosPersonales)
                            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMesajeConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                            .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jLabel6))
                                                        .addGap(22, 22, 22))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNuevoClienteLayout.createSequentialGroup()
                                                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                                    .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblApellidoCliente)
                                                        .addComponent(jLabel7)
                                                        .addComponent(lblNombreCliente)
                                                        .addComponent(jLabel8))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtApellidoCliente)
                                                .addComponent(txtCodigoPostal)
                                                .addComponent(txtNombreCliente)
                                                .addComponent(txtNacionalidad)
                                                .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                                    .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                                            .addComponent(ddlTipodocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                                            .addComponent(jLabel3)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(ddlDiaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                                            .addComponent(jLabel4)
                                                            .addGap(2, 2, 2)))
                                                    .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                                            .addComponent(ddlMesNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel5)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(ddlAnioNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                                            .addComponent(jLabel17)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(txtDocCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createSequentialGroup()
                                                    .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                                        .addComponent(txtDepartamento))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel18))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNumero)
                                                        .addComponent(txtPiso)))
                                                .addComponent(txtCodigo))))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))))
                        .addGap(57, 57, 57)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createSequentialGroup()
                                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                        .addComponent(txtNombreConocido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtApellidoConocido, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                        .addComponent(txtOtroTelefono)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAgregarConocido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createSequentialGroup()
                                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(lblGarante))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addComponent(btnGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(txtCelular))))))
                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarCliente)))
                .addContainerGap())
        );
        pnlNuevoClienteLayout.setVerticalGroup(
            pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosPersonales)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createSequentialGroup()
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblNombreCliente)
                                .addGap(18, 18, 18))
                            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGarante, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGarante)))
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ddlTipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtDocCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombreConocido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtApellidoConocido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtOtroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarConocido))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(ddlDiaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(ddlMesNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(ddlAnioNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevoClienteLayout.createSequentialGroup()
                                .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoClienteLayout.createSequentialGroup()
                                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCliente)
                    .addComponent(lblMesajeConfirmacion))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout pnlTituloAdministracionClienteLayout = new javax.swing.GroupLayout(pnlTituloAdministracionCliente);
        pnlTituloAdministracionCliente.setLayout(pnlTituloAdministracionClienteLayout);
        pnlTituloAdministracionClienteLayout.setHorizontalGroup(
            pnlTituloAdministracionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTituloAdministracionClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloAdministracionClienteLayout.setVerticalGroup(
            pnlTituloAdministracionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAdministracionClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAdministracionClienteLayout = new javax.swing.GroupLayout(pnlAdministracionCliente);
        pnlAdministracionCliente.setLayout(pnlAdministracionClienteLayout);
        pnlAdministracionClienteLayout.setHorizontalGroup(
            pnlAdministracionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloAdministracionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAdministracionClienteLayout.setVerticalGroup(
            pnlAdministracionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdministracionClienteLayout.createSequentialGroup()
                .addComponent(pnlTituloAdministracionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlAdministracionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlAdministracionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void btnGuardarGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGaranteActionPerformed
        SaveGarante();
        btnGarante.setText("Modificar Garante");
        jdGarante.setVisible(false);
    }//GEN-LAST:event_btnGuardarGaranteActionPerformed

    private void txtNombreGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGaranteActionPerformed

    private void btnGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaranteActionPerformed
        ObjectGaranteToForm();
        jdGarante.setVisible(true);
    }//GEN-LAST:event_btnGaranteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        saveCliente();
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnAgregarConocidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConocidoActionPerformed
        Conocido conocido = FormToObjectConocido();                
        SaveConocido(conocido);        
    }//GEN-LAST:event_btnAgregarConocidoActionPerformed

    private void lstOtroscontactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstOtroscontactosMouseClicked
        String selectedItem = lstOtroscontactos.getSelectedValue().toString();
        selectedIndexConocido = lstOtroscontactos.getSelectedIndex();
        Conocido conocido = (Conocido)conocidos.get(selectedItem);
        ObjectConocidoToForm(conocido);
    }//GEN-LAST:event_lstOtroscontactosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarConocido;
    private javax.swing.JButton btnGarante;
    private javax.swing.JButton btnGuardarGarante;
    private javax.swing.JComboBox ddlAnioNacimiento;
    private javax.swing.JComboBox ddlDiaNacimiento;
    private javax.swing.JComboBox ddlMesNacimiento;
    private javax.swing.JComboBox ddlTipodocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JDialog jdGarante;
    private javax.swing.JLabel lblApellidoCliente;
    private javax.swing.JLabel lblDatosPersonales;
    private javax.swing.JLabel lblGarante;
    private javax.swing.JLabel lblMesajeConfirmacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTituloNuevoCliente;
    private javax.swing.JList lstOtroscontactos;
    public javax.swing.JPanel pnlAdministracionCliente;
    public javax.swing.JPanel pnlNuevoCliente;
    public javax.swing.JPanel pnlTituloAdministracionCliente;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtApellidoConocido;
    private javax.swing.JTextField txtApellidoGarante;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtCodigoPostalGarante;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDepartamentoGarante;
    private javax.swing.JFormattedTextField txtDocCliente;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtDomicilioGarante;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JFormattedTextField txtNombreConocido;
    private javax.swing.JTextField txtNombreGarante;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JTextField txtNumeroGarante;
    private javax.swing.JFormattedTextField txtOtroTelefono;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtPisoGarante;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void setDatosIniciales() {
        colaborador = new NuevoClienteColaborador();
        conocidosABorrar = new ArrayList<>();
        fillCombos();
        jdGarante.setSize(450,350);
    }

    private void fillCombos() {        
        Commons.loadCombo(ddlTipodocumento, colaborador.getTiposDocumento());
        Commons.loadCombo(ddlAnioNacimiento, colaborador.getAnios());
    }

    private void saveCliente() {
        Cliente c = getClienteFormulario();        
        c.setGarante(garante);
        ObjectValidator validador = colaborador.isValidCliente(c);
        if(validador.isIsValid()){
            idCliente = colaborador.Save(c);
            colaborador.DeleteConocidos(conocidosABorrar);
            if( idCliente != null){
                c = colaborador.GetClienteById(idCliente);
                txtCodigo.setText(c.getCodigo());
                lblMesajeConfirmacion.setForeground(new Color(0, 153, 51));
                lblMesajeConfirmacion.setText("Se guardo el Cliente con éxito");
            }else{
                lblMesajeConfirmacion.setForeground(Color.red);
                lblMesajeConfirmacion.setText("No se pudo guardar el Cliente. Intentelo otra vez");
            }
        }else
            JOptionPane.showMessageDialog(rootPane, validador.getMessage(), "Mensaje de Error", 1);
    }

    private Cliente getClienteFormulario() {
        Cliente c = null;
        if(idCliente == null)
            c = new Cliente();      
        else
            c = (Cliente)colaborador.GetClienteById(idCliente);
            
        // Datos generales del cliente
        c.setNombre(txtNombreCliente.getText());
        c.setApellido(txtApellidoCliente.getText());
        c.setNacionalidad(txtNacionalidad.getText());
        c.setTipoDocumento(colaborador.getTipoDocumentoById(((ComboItem)ddlTipodocumento.getSelectedItem()).getKey()));
        c.setNumeroDocumento(!txtDocCliente.getText().equals("") ? Integer.parseInt(txtDocCliente.getText()) : 0);
        c.setFechaNacimiento(colaborador.getDate(ddlDiaNacimiento.getSelectedItem().toString(), 
                                                 ddlMesNacimiento.getSelectedItem().toString(), 
                                                 ddlAnioNacimiento.getSelectedItem().toString()));
        c.setTelefono(txtTelefono.getText().replaceAll("-", ""));
        c.setCelular(txtCelular.getText().replaceAll("-", ""));
        // Datos de Dirección
        Direccion direccion = new Direccion();
        direccion.setCalle(txtDomicilio.getText());
        direccion.setNumero(!txtNumero.getText().trim().equals("") ? Integer.parseInt(txtNumero.getText()) : 0);
        direccion.setCodigoPostal(txtCodigoPostal.getText());
        c.setDireccion(direccion);
        c.setConocidos(colaborador.getConocidosCliente(conocidos));
        return c;
    }

    private void SaveGarante() {
        garante = new Garante();
        garante.setNombre(txtNombreGarante.getText());
        garante.setApellido(txtApellidoGarante.getText());
        Direccion dirGarante = new Direccion();
        dirGarante.setCalle(txtDomicilioGarante.getText());
        dirGarante.setNumero(Integer.parseInt(txtNumeroGarante.getText()));
        dirGarante.setCodigoPostal(txtCodigoPostalGarante.getText());
        dirGarante.setDepartamento(txtDepartamentoGarante.getText());
        dirGarante.setPiso(txtPisoGarante.getText());
        garante.setDireccion(dirGarante);
    }

    private void ObjectGaranteToForm() {
        if(garante != null){
            txtNombreGarante.setText(garante.getNombre());
            txtApellidoGarante.setText(garante.getApellido());
            Direccion direccion = garante.getDireccion();
            txtDomicilioGarante.setText(direccion.getCalle());
            txtNumeroGarante.setText(direccion.getNumero()!= 0 ? direccion.getNumero().toString() : "");
            txtPisoGarante.setText(direccion.getPiso());
            txtDepartamentoGarante.setText(direccion.getDepartamento());
        }
    }

    private void setClienteFormulario(int idCliente) {
        this.idCliente = idCliente;        
        ObjectClienteToForm((Cliente)colaborador.GetClienteById(idCliente));
        btnGarante.setText("Modificar Garante");
    }
    
    private void ObjectClienteToForm(Cliente c){
        txtNombreCliente.setText(c.getNombre());
        txtApellidoCliente.setText(c.getApellido());
        txtNacionalidad.setText(c.getNacionalidad());
        
        ddlTipodocumento.setSelectedItem(Commons.getItemByKey(c.getTipoDocumento().getId(), ddlTipodocumento));
        txtDocCliente.setText(c.getNumeroDocumento().toString());        
        Calendar cal = Calendar.getInstance();
        cal.setTime(c.getFechaNacimiento());
        Integer anio = cal.get(Calendar.YEAR);
        Integer mes = cal.get(Calendar.MONTH)+1;
        Integer dia = cal.get(Calendar.DAY_OF_MONTH);
        ddlDiaNacimiento.setSelectedItem(dia.toString());
        ddlMesNacimiento.setSelectedItem(mes.toString());
        ddlAnioNacimiento.setSelectedItem(Commons.getItemByKey(anio, ddlAnioNacimiento));
        txtTelefono.setText(c.getTelefono());
        txtCelular.setText(c.getCelular());
        Direccion direccion = c.getDireccion();
        txtDomicilio.setText(direccion.getCalle());
        txtNumero.setText(direccion.getNumero().toString());
        txtCodigoPostal.setText(direccion.getCodigoPostal());
        garante = c.getGarante();
        txtCodigo.setText(c.getCodigo());
        ObjectGaranteToForm(); 
        for(Conocido conocido : c.getConocidos()){            
            String item = colaborador.getNombreCompletoYTelefono(conocido);
            conocidos.put(item, conocido);
            lstOtroscontactos.setModel(colaborador.getModelConocidos(item));            
        }
    }

    private void SaveConocido(Conocido conocido) {        
        ObjectValidator conocidoValidator = new ConocidoValidator(conocido);
        String item = colaborador.getNombreCompletoYTelefono(conocido);
        if(conocidoValidator.isIsValid()){
            if(selectedIndexConocido == null){                
                conocidos.put(item, conocido);
                lstOtroscontactos.setModel(colaborador.getModelConocidos(item));            
            }else{
                String selectedItem = lstOtroscontactos.getSelectedValue().toString();
                conocidosABorrar.add(selectedIndexConocido);
                conocidos.remove(selectedItem);
                conocidos.put(item, conocido);    
                colaborador.setModelLstOtrosContactos(selectedIndexConocido, item);                  
            }
            
            CleanFormConocido();
        }else
            JOptionPane.showMessageDialog(rootPane, conocidoValidator.getMessage(), "Mensaje de Error", 1);        
    }

    private void CleanFormConocido() {
        txtNombreConocido.setText("");
        txtApellidoConocido.setText("");
        txtOtroTelefono.setText("");
        selectedIndexConocido = null;
        lstOtroscontactos.clearSelection();
    }

    private Conocido FormToObjectConocido() {
        Conocido conocido = new Conocido();
        conocido.setApellido(txtApellidoConocido.getText());
        conocido.setNombre(txtNombreConocido.getText());
        conocido.setTelefono(txtOtroTelefono.getText());
        
        return conocido;
    }
    
    private void ObjectConocidoToForm(Conocido conocido){
        txtApellidoConocido.setText(conocido.getApellido());
        txtNombreConocido.setText(conocido.getNombre());
        txtOtroTelefono.setText(conocido.getTelefono());
    }


    private Conocido UpdateConocido(String selectedItem) {
        Conocido conocidoViejo = (Conocido)conocidos.get(selectedItem);
        conocidos.remove(selectedItem);
        if(conocidoViejo != null && conocidoViejo.getId()!= 0){
            Conocido conocido = colaborador.GetConocidoById(conocidoViejo.getId());
            conocido.setApellido(txtApellidoConocido.getText());
            conocido.setNombre(txtNombreConocido.getText());
            conocido.setTelefono(txtOtroTelefono.getText());
            return conocido;
        }
        
        return new Conocido();
    }
}
