package prestamo.Modelo;
// Generated Apr 16, 2014 12:39:12 PM by Hibernate Tools 3.6.0



/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {


     private int id;
     private Garante garanteCliente;

    public Cliente() {
    }

	
    public Cliente(int id) {
        this.id = id;
    }
    public Cliente(int id, Garante garanteCliente) {
       this.id = id;
       this.garanteCliente = garanteCliente;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public Garante getGarante() {
        return this.garanteCliente;
    }
    
    public void setGarante(Garante garante) {
        this.garanteCliente = garante;
    }
}


