package prestamo.Modelo;
// Generated Jul 15, 2014 5:35:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,schema="prestamo"
)
public class Cliente extends Persona  {


     private String ocupacion;
     private Garante garante;
     private Set<Conocido> conocidos = new HashSet<>();

    public Cliente() {
    }

    public Cliente(String apellido, String nombre, Integer numeroDocumento, TipoDocumento tipoDocumento, String ocupacion, Direccion direccion, Garante garante, Set<Conocido>conocidos ) {
       super(apellido, nombre, numeroDocumento, tipoDocumento, direccion);        
       this.ocupacion = ocupacion;
       this.garante = garante;
       this.conocidos = conocidos;
    }

    
    @Column(name="ocupacion")
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name = "id_garante")
    public Garante getGarante() {
        return this.garante;
    }
    
    public void setGarante(Garante garante){
        this.garante = garante;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Conocido> getConocidos(){
        return this.conocidos;
    }
    
    public void setConocidos(Set<Conocido> conocidos){
        this.conocidos = conocidos;
    }
}
