package prestamo.Modelo;
// Generated 28/07/2014 00:25:40 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuota generated by hbm2java
 */
@Entity
@Table(name="cuota"
    ,schema="prestamo"
)
public class Cuota  implements java.io.Serializable, Comparable<Cuota> {


     private int id;
     private Prestamo prestamo;
     private Integer numeroCuota;
     private BigDecimal monto;
     private BigDecimal saldoInicial;
     private BigDecimal interesPeriodo;
     private BigDecimal amortizacion;
     private BigDecimal totalAmortizado;
     private Date fechaCuota;
     

    public Cuota() {
    }

	
    public Cuota(int id) {
        this.id = id;
    }
    public Cuota(int id, Prestamo prestamo, Integer numeroCuota, BigDecimal monto) {
       this.id = id;
       this.prestamo = prestamo;
       this.numeroCuota = numeroCuota;
       this.monto = monto;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_prestamo")
    public Prestamo getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(Prestamo prestamo) {
        this.prestamo = prestamo;
    }

    
    @Column(name="numero_cuota")
    public Integer getNumeroCuota() {
        return this.numeroCuota;
    }
    
    public void setNumeroCuota(Integer numeroCuota) {
        this.numeroCuota = numeroCuota;
    }

    
    @Column(name="monto", precision=131089, scale=0)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    @Column(name="saldo_inicial", precision=131089, scale=0)
    public BigDecimal getSaldoInicial() {
        return saldoInicial;
    }

    /**
     * @param saldoInicial the saldoInicial to set
     */
    public void setSaldoInicial(BigDecimal saldoInicial) {
        this.saldoInicial = saldoInicial;
    }

    @Column(name="interes_periodo", precision=131089, scale=0)
    public BigDecimal getInteresPeriodo() {
        return interesPeriodo;
    }

    /**
     * @param interesPeriodo the interesPeriodo to set
     */
    public void setInteresPeriodo(BigDecimal interesPeriodo) {
        this.interesPeriodo = interesPeriodo;
    }

    @Column(name="amortizacion", precision=131089, scale=0)
    public BigDecimal getAmortizacion() {
        return amortizacion;
    }

    /**
     * @param amortizacion the amortización to set
     */
    public void setAmortizacion(BigDecimal amortizacion) {
        this.amortizacion = amortizacion;
    }

    @Column(name="total_amortizado", precision=131089, scale=0)
    public BigDecimal getTotalAmortizado() {
        return totalAmortizado;
    }

    /**
     * @param totalAmortizado the totalAmortizado to set
     */
    public void setTotalAmortizado(BigDecimal totalAmortizado) {
        this.totalAmortizado = totalAmortizado;
    }

    @Override
    public int compareTo(Cuota c) {
        if (numeroCuota < c.numeroCuota) {
            return -1;
        }
        if (numeroCuota > c.numeroCuota) {
            return 1;
        }
        return 0;        
    }

    /**
     * @return the fechaCuota
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_cuota", length=29)
    public Date getFechaCuota() {
        return fechaCuota;
    }

    /**
     * @param fechaCuota the fechaCuota to set
     */
    public void setFechaCuota(Date fechaCuota) {
        this.fechaCuota = fechaCuota;
    }
    
    public String FechaCuotaString(){
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy", new Locale("es_ES"));
        String fechaString = "";
        
        if(fechaCuota != null){
            fechaString = formateador.format(fechaCuota);
        }
        return fechaString;
    }
}
