package prestamo.Modelo;
// Generated Jul 15, 2014 5:35:39 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name="direccion"
    ,schema="prestamo"
)
public class Direccion  implements java.io.Serializable {


     private int id;
     private Localidad localidad;
     private String calle;
     private Integer numero;
     private String piso;
     private String departamento;
     private String codigoPostal;

    public Direccion() {
    }

	
    public Direccion(int id) {
        this.id = id;
    }
    public Direccion(int id, Localidad localidad, String calle, Integer numero, String piso, String departamento) {
       this.id = id;
       this.localidad = localidad;
       this.calle = calle;
       this.numero = numero;
       this.piso = piso;
       this.departamento = departamento;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_localidad")
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }

    
    @Column(name="calle")
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    
    @Column(name="piso")
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }

    
    @Column(name="departamento")
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    
    @Column(name="codigo_postal")
    public String getCodigoPostal() {
        return this.departamento;
    }
    
    public void setCodigoPostal(String codigoPostal){
        this.codigoPostal = codigoPostal;
    }
}
