package prestamo.Modelo;
// Generated Apr 16, 2014 12:39:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;

/**
 * Garante generated by hbm2java
 */
public class Garante  implements java.io.Serializable {


    private int id;
    
    
    public Garante(){
    }
	
    public Garante(int id) {
        this.id = id;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
}


