package prestamo.Modelo;
// Generated Apr 16, 2014 12:39:12 PM by Hibernate Tools 3.6.0



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private Integer idTipoDocumento;
     private String nroDocumento;

    public Persona() {
    }

	
    public Persona(int id) {
        this.id = id;
    }
    public Persona(int id, String nombre, String apellido, Integer idTipoDocumento, String nroDocumento) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.idTipoDocumento = idTipoDocumento;
       this.nroDocumento = nroDocumento;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Integer idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(String nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
}


