package prestamo.Modelo;
// Generated Apr 16, 2014 12:39:12 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private int id;
     private BigDecimal montoTotal;
     private Integer idCliente;

    public Prestamo() {
    }

	
    public Prestamo(int id) {
        this.id = id;
    }
    public Prestamo(int id, BigDecimal montoTotal, Integer idCliente) {
       this.id = id;
       this.montoTotal = montoTotal;
       this.idCliente = idCliente;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BigDecimal getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }




}


